### ISSUE TITLE
No ercot_2016/2017/2018.xlsx

### ISSUE THREAD

**Issue by zbs881314** [MinseungKo/DRNet#1]
Could you share the three datasets ercot_2016.xlsx, ercot_2017.xlsx, ercot_2018.xlsx?

**Comment by luckyboyjeff** [comment]
> 你能分享三个数据集 ercot_2016.xlsx、ercot_2017.xlsx、ercot_2018.xlsx 吗？
Hi, did you find the dataset for ercot?

**Comment by hudaraon** [comment]
你好，请问ercot2016-2017的数据集还有吗？网站上只找到2022年的，我的邮箱是hubin7331@163.com，非常感谢！

**Comment by FanHaveFun** [comment]
thanks for your nice work! but I can't download the three datasets.
could you share the three datasets ercot_2016.xlsx, ercot_2017.xlsx, ercot_2018.xlsx.
my email:fangoodlike321@gmail.com
best wishes!

**Comment by MinseungKo** [comment]
Please check out the following attached files.
The original source of these files is "https://www.ercot.com/gridinfo".

[ercot_2017.xlsx](https://github.com/MinseungKo/DRNet/files/8794700/ercot_2017.xlsx)
[ercot_2018.xlsx](https://github.com/MinseungKo/DRNet/files/8794701/ercot_2018.xlsx)
[ercot_2016.xlsx](https://github.com/MinseungKo/DRNet/files/8794702/ercot_2016.xlsx)

**Comment by ykp-ykp** [comment]
thank you！
